# tests/test_metrics.py — rmse and inlier_stats against fabricated MatchResults
# with known, hand-checkable answers. No real matcher or imagery involved.

import numpy as np
import pytest

from src.metrics import rmse, inlier_stats
from src.types import MatchResult


def _homography(rotation_deg=10.0, tx=5.0, ty=-3.0):
    theta = np.deg2rad(rotation_deg)
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s, tx], [s, c, ty], [0, 0, 1]], dtype=np.float64)


def _apply(H, pts):
    ones = np.ones((len(pts), 1))
    homog = np.hstack([pts, ones])
    projected = (H @ homog.T).T
    return (projected[:, :2] / projected[:, 2:3]).astype(np.float32)


def _match_result(pts_a, pts_b, inlier_mask, transform, shape=(256, 256)):
    n = len(pts_a)
    return MatchResult(
        pts_a=pts_a.astype(np.float32),
        pts_b=pts_b.astype(np.float32),
        scores=np.ones(n, dtype=np.float32),
        inlier_mask=inlier_mask.astype(bool),
        transform=transform.astype(np.float64),
        matcher="synth",
        shape_a=shape,
        shape_b=shape,
        runtime_s=0.0,
    )


# ---- rmse ------------------------------------------------------------------

def test_rmse_of_perfect_matches_is_near_zero():
    rng = np.random.default_rng(0)
    H = _homography()
    pts_a = rng.uniform(0, 256, size=(200, 2)).astype(np.float32)
    pts_b = _apply(H, pts_a)  # no noise -- H maps a to b exactly

    mr = _match_result(pts_a, pts_b, np.ones(200, dtype=bool), transform=H)

    result = rmse(mr, gt_transform=H)
    assert result["rmse_fitted"] == pytest.approx(0.0, abs=1e-3)
    assert result["rmse_ground_truth"] == pytest.approx(0.0, abs=1e-3)


def test_rmse_perfect_translation_of_four_corners_by_hand():
    """The simplest possible case, computable with no library at all: four
    corner points shifted by a known (+5, +2) translation. If the fitted
    transform is exactly that shift, RMSE must be exactly 0.
    """
    pts_a = np.array([[0, 0], [10, 0], [0, 10], [10, 10]], dtype=np.float32)
    pts_b = pts_a + np.array([5, 2], dtype=np.float32)
    transform = np.array([[1, 0, 5], [0, 1, 2], [0, 0, 1]], dtype=np.float64)

    mr = _match_result(pts_a, pts_b, np.ones(4, dtype=bool), transform)

    result = rmse(mr)
    assert result["rmse_fitted"] == pytest.approx(0.0, abs=1e-5)


def test_rmse_known_per_point_pixel_errors_computed_by_hand():
    """Four points evaluated against the identity transform, with deliberately
    chosen per-point errors: 1px, 2px, 0px, 0px. Hand-computed RMSE:
    sqrt((1^2 + 2^2 + 0^2 + 0^2) / 4) = sqrt(1.25) ~= 1.11803. A much
    stronger check than `rmse(...) > 0` -- it pins down the exact formula.
    """
    pts_a = np.array([[0, 0], [10, 0], [0, 10], [10, 10]], dtype=np.float32)
    pts_b = np.array([[1, 0], [10, 2], [0, 10], [10, 10]], dtype=np.float32)  # errors: 1, 2, 0, 0
    identity = np.eye(3, dtype=np.float64)

    mr = _match_result(pts_a, pts_b, np.ones(4, dtype=bool), identity)

    result = rmse(mr)
    expected = np.sqrt((1 ** 2 + 2 ** 2 + 0 ** 2 + 0 ** 2) / 4)
    assert result["rmse_fitted"] == pytest.approx(expected, abs=1e-5)


def test_rmse_ground_truth_diverges_from_a_biased_fitted_transform():
    """Distinguishes the two return values by construction: the *true*
    correspondence follows a (+5, +10) translation exactly (gt_transform),
    but the *fitted* transform stored on the MatchResult is slightly wrong,
    (+6, +10) -- as if RANSAC's fit carried a 1px bias. rmse_ground_truth
    must come out 0 (it matches how pts_b was actually generated);
    rmse_fitted must come out exactly 1.0 (the x-axis bias, on every point).
    """
    pts_a = np.array([[0, 0], [10, 0], [0, 10], [10, 10]], dtype=np.float32)
    gt_transform = np.array([[1, 0, 5], [0, 1, 10], [0, 0, 1]], dtype=np.float64)
    fitted_transform = np.array([[1, 0, 6], [0, 1, 10], [0, 0, 1]], dtype=np.float64)

    pts_b = pts_a + np.array([5, 10], dtype=np.float32)  # generated by gt_transform, exactly

    mr = _match_result(pts_a, pts_b, np.ones(4, dtype=bool), fitted_transform)

    result = rmse(mr, gt_transform=gt_transform)
    assert result["rmse_ground_truth"] == pytest.approx(0.0, abs=1e-5)
    assert result["rmse_fitted"] == pytest.approx(1.0, abs=1e-5)


def test_rmse_reflects_known_injected_noise():
    """Same trick as the team's testing philosophy elsewhere: inject noise of
    a chosen std and check the RMSE recovers it. For 2D error with independent
    per-axis Gaussian noise of std sigma, E[error^2] = 2*sigma^2, so the
    expected RMSE is sigma*sqrt(2) -- not sigma itself.
    """
    rng = np.random.default_rng(1)
    H = _homography()
    sigma = 0.3
    pts_a = rng.uniform(0, 256, size=(400, 2)).astype(np.float32)
    pts_b = _apply(H, pts_a) + rng.normal(0, sigma, size=(400, 2)).astype(np.float32)

    mr = _match_result(pts_a, pts_b, np.ones(400, dtype=bool), transform=H)

    result = rmse(mr, gt_transform=H)
    expected = sigma * np.sqrt(2)
    assert result["rmse_fitted"] == pytest.approx(expected, rel=0.15)
    assert result["rmse_ground_truth"] == pytest.approx(expected, rel=0.15)


def test_rmse_ignores_outliers_outside_the_inlier_mask():
    rng = np.random.default_rng(2)
    H = _homography()
    pts_a = rng.uniform(0, 256, size=(50, 2)).astype(np.float32)
    pts_b = _apply(H, pts_a)

    # corrupt half the points with a huge offset, but mark them as outliers
    pts_b_corrupted = pts_b.copy()
    pts_b_corrupted[25:] += 1000.0
    inlier_mask = np.array([True] * 25 + [False] * 25)

    mr = _match_result(pts_a, pts_b_corrupted, inlier_mask, transform=H)

    result = rmse(mr, gt_transform=H)
    assert result["rmse_fitted"] == pytest.approx(0.0, abs=1e-3)


def test_rmse_ground_truth_is_none_when_not_supplied():
    rng = np.random.default_rng(3)
    H = _homography()
    pts_a = rng.uniform(0, 256, size=(20, 2)).astype(np.float32)
    pts_b = _apply(H, pts_a)

    mr = _match_result(pts_a, pts_b, np.ones(20, dtype=bool), transform=H)

    result = rmse(mr)
    assert result["rmse_ground_truth"] is None
    assert result["rmse_fitted"] == pytest.approx(0.0, abs=1e-3)


def test_rmse_of_empty_match_result_is_nan_not_zero():
    empty = np.zeros((0, 2), dtype=np.float32)
    mr = _match_result(empty, empty, np.zeros(0, dtype=bool), transform=np.eye(3))

    result = rmse(mr, gt_transform=np.eye(3))
    assert np.isnan(result["rmse_fitted"])
    assert np.isnan(result["rmse_ground_truth"])


def test_rmse_with_no_inliers_among_many_matches_is_nan():
    rng = np.random.default_rng(4)
    H = _homography()
    pts_a = rng.uniform(0, 256, size=(30, 2)).astype(np.float32)
    pts_b = _apply(H, pts_a)
    mr = _match_result(pts_a, pts_b, np.zeros(30, dtype=bool), transform=H)  # all outliers

    result = rmse(mr)
    assert np.isnan(result["rmse_fitted"])


# ---- inlier_stats ------------------------------------------------------------

def test_inlier_stats_hand_checkable_count_and_ratio():
    mask = np.array([True] * 7 + [False] * 3)
    mr = _match_result(np.zeros((10, 2), dtype=np.float32), np.zeros((10, 2), dtype=np.float32), mask, np.eye(3))

    stats = inlier_stats(mr)
    assert stats == {"inlier_count": 7, "total_matches": 10, "inlier_ratio": pytest.approx(0.7)}


def test_inlier_stats_all_inliers():
    mask = np.ones(15, dtype=bool)
    mr = _match_result(np.zeros((15, 2), dtype=np.float32), np.zeros((15, 2), dtype=np.float32), mask, np.eye(3))

    stats = inlier_stats(mr)
    assert stats["inlier_ratio"] == pytest.approx(1.0)
    assert stats["inlier_count"] == 15


def test_inlier_stats_no_inliers():
    mask = np.zeros(8, dtype=bool)
    mr = _match_result(np.zeros((8, 2), dtype=np.float32), np.zeros((8, 2), dtype=np.float32), mask, np.eye(3))

    stats = inlier_stats(mr)
    assert stats["inlier_ratio"] == pytest.approx(0.0)
    assert stats["inlier_count"] == 0


def test_inlier_stats_single_match_is_not_assumed_to_need_many_points():
    mask = np.array([True])
    mr = _match_result(np.zeros((1, 2), dtype=np.float32), np.zeros((1, 2), dtype=np.float32), mask, np.eye(3))

    stats = inlier_stats(mr)
    assert stats == {"inlier_count": 1, "total_matches": 1, "inlier_ratio": pytest.approx(1.0)}


def test_inlier_stats_of_empty_match_result_is_zero_ratio_not_nan():
    empty = np.zeros((0, 2), dtype=np.float32)
    mr = _match_result(empty, empty, np.zeros(0, dtype=bool), transform=np.eye(3))

    stats = inlier_stats(mr)
    assert stats == {"inlier_count": 0, "total_matches": 0, "inlier_ratio": 0.0}
    assert not np.isnan(stats["inlier_ratio"])
