import React, { useState, useEffect } from 'react';
import { BarChart3, ShieldCheck, ArrowRight, ArrowLeft, AlertTriangle, Loader2 } from 'lucide-react';

const API_BASE = 'http://127.0.0.1:8000';

export default function Screen03Evidence({ jobId, selectedProductA, selectedProductB, onProceedToExport, onBack }) {
  const [status, setStatus] = useState('fetching'); // fetching, ready, failed
  const [metrics, setMetrics] = useState(null);
  const [errorMsg, setErrorMsg] = useState(null);

  const prodA_id = selectedProductA?.product_id || 'Unknown Product';
  const prodB_id = selectedProductB?.product_id || 'Unknown Product';

  useEffect(() => {
    let isMounted = true;

    const fetchArtefacts = async () => {
      if (!jobId) {
        if (isMounted) {
          setErrorMsg("Missing job ID from previous step. Please go back and run a match.");
          setStatus('failed');
        }
        return;
      }

      try {
        const metricsRes = await fetch(`${API_BASE}/jobs/${jobId}/artefacts/metrics.json`);
        if (!metricsRes.ok) throw new Error("Failed to fetch metrics.json");
        const metricsData = await metricsRes.json();

        if (isMounted) {
          setMetrics(metricsData);
          setStatus('ready');
        }
      } catch (err) {
        if (isMounted) {
          setErrorMsg(err.message || "Failed to fetch evidence artefacts.");
          setStatus('failed');
        }
      }
    };

    fetchArtefacts();

    return () => {
      isMounted = false;
    };
  }, [jobId]);

  if (status === 'failed') {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh] space-y-4 animate-fadeIn">
        <AlertTriangle className="w-12 h-12 text-red-500" />
        <h2 className="text-xl font-bold text-slate-200">Missing Evidence Data</h2>
        <p className="text-slate-500 font-mono text-sm">{errorMsg}</p>
        {onBack && (
          <button onClick={onBack} className="mt-4 flex items-center space-x-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-md transition">
            <ArrowLeft className="w-4 h-4" />
            <span>Return to Review</span>
          </button>
        )}
      </div>
    );
  }

  if (status !== 'ready') {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh] space-y-6 animate-fadeIn">
        <Loader2 className="w-10 h-10 animate-spin text-cyan-500" />
        <div className="text-center space-y-2">
          <h2 className="text-lg font-display font-semibold text-slate-200">
            Retrieving Match Evidence...
          </h2>
          <p className="text-sm font-mono text-cyan-400">
            {prodA_id} → {prodB_id}
          </p>
          <p className="text-xs font-mono text-slate-500 mt-2">Loading backend artefacts...</p>
        </div>
      </div>
    );
  }

  // Safe Metric Formatters
  const safeNum = (val, decimals = 2) => {
    if (val === null || val === undefined || isNaN(Number(val))) return "N/A";
    return Number(val).toFixed(decimals);
  };

  return (
    <div className="space-y-6 animate-fadeIn pb-12">
      <div className="border-b border-[#2a2a2a] pb-4">
        <h2 className="text-lg font-display font-semibold text-slate-200 flex items-center space-x-2">
          <BarChart3 className="w-5 h-5 text-cyan-400" />
          <span>Evidence</span>
        </h2>
        <p className="text-xs text-slate-500 font-mono mt-0.5">
          Does illumination-robust matching survive extreme sun-angle change? Real DEM sweep results, generated by
          src/sweep.py + src/match.py -- not recomputed live per pair.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-4">
          <div className="glass-panel p-4 space-y-2">
            <h3 className="text-sm font-mono font-semibold text-slate-300 uppercase tracking-wide">
              Inlier count vs. sun-azimuth difference
            </h3>
            <img src={`${API_BASE}/evidence/win_plot.png`} alt="Win plot" className="w-full rounded-md border border-[#2a2a2a]" />
          </div>

          <div className="glass-panel p-4 space-y-2">
            <h3 className="text-sm font-mono font-semibold text-slate-300 uppercase tracking-wide">
              Match coverage vs. sun-azimuth difference
            </h3>
            <p className="text-xs text-slate-500">
              The statement's "uniform distribution" requirement, made visible -- fraction of an 8×8 grid containing
              at least one inlier.
            </p>
            <img src={`${API_BASE}/evidence/coverage_plot.png`} alt="Coverage plot" className="w-full rounded-md border border-[#2a2a2a]" />
          </div>
        </div>

        <div className="space-y-4">
          <div className="glass-panel p-5 space-y-3 font-mono text-xs">
            <div className="flex items-center justify-between text-cyan-400 font-semibold border-b border-[#2a2a2a] pb-2">
              <span>THIS JOB'S RESULT</span>
              <ShieldCheck className="w-4 h-4 text-cyan-400" />
            </div>

            {metrics?.trivial_fit && (
              <div className="flex items-start space-x-2 bg-amber-950/30 border border-amber-800 rounded-md p-2.5">
                <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
                <span className="text-[11px] text-amber-200">Trivial fit -- not a validated registration.</span>
              </div>
            )}

            <div className="space-y-2.5">
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Job ID:</span>
                <span className="text-cyan-400 font-semibold text-[10px]">{jobId}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Total Matches:</span>
                <span className="text-slate-200 font-medium">{safeNum(metrics?.total_matches, 0)}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Inlier Count:</span>
                <span className="text-emerald-400 font-medium">{safeNum(metrics?.inlier_count, 0)}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Inlier Ratio:</span>
                <span className="text-emerald-400 font-medium">{metrics?.inlier_ratio !== undefined && metrics?.inlier_ratio !== null ? safeNum(metrics.inlier_ratio * 100, 1) + '%' : 'N/A'}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Sub-pixel RMSE:</span>
                <span className="text-cyan-400 font-semibold">{safeNum(metrics?.reprojection_residual, 3)} px</span>
              </div>
              {metrics?.rmse_ground_truth !== undefined && metrics?.rmse_ground_truth !== null && (
                <div className="flex justify-between items-center">
                  <span className="text-slate-500">RMSE (Ground Truth):</span>
                  <span className="text-slate-200 font-medium">{safeNum(metrics?.rmse_ground_truth, 3)} px</span>
                </div>
              )}
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Grid Coverage:</span>
                <span className="text-slate-200 font-medium">{safeNum((metrics?.occupied_fraction || 0) * 100, 1)}%</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Distribution CV:</span>
                <span className="text-slate-200 font-medium">{safeNum(metrics?.coefficient_of_variation, 2)}</span>
              </div>
            </div>
          </div>

          {/* Spatial grid heatmap -- honestly not implemented, not faked */}
          <div className="glass-panel p-4 space-y-2">
            <div className="text-xs font-mono text-slate-400 font-semibold">
              UNIFORM DISTRIBUTION MATRIX
            </div>
            <div className="bg-[#0a0a0a] p-4 rounded-md border border-[#2a2a2a] text-center text-slate-500 font-mono text-[10px]">
              <p className="font-semibold text-slate-400">Spatial grid heatmap is disabled.</p>
              <p className="mt-1 text-slate-600">The backend does not expose the 8x8 cell density array in metrics.json.</p>
            </div>
          </div>

          <button
            onClick={onProceedToExport}
            className="w-full flex items-center justify-center space-x-2 py-2.5 rounded-md glow-btn-cyan text-xs font-mono font-semibold transition"
          >
            <span>Proceed to Terrain &amp; Export</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
}
