import asyncio
import csv
import json
import sqlite3
import os
import uuid
import traceback
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from fastapi import FastAPI, BackgroundTasks, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

import numpy as np

from src.pipeline import run_pipeline
from src.deliverable import build_deliverable
from src.cnet import write_control_network
from src.types import MatchResult, Product
from src.geo import footprint_overlap
import src.io_lro as io_lro
import src.io_ch2 as io_ch2
import src.catalog as catalog
from tests.make_synthetic import make_synthetic_pair

app = FastAPI(title="LunarMatch API", description="API and Job Store for Member 5")

# The frontend runs on a different origin (Vite dev server, localhost:3000)
# than this API (127.0.0.1:8000) -- without CORS headers the browser blocks
# every fetch() call with no useful error, which is exactly what surfaced as
# "Failed to connect to LunarMatch backend" despite the API being reachable
# (curl/server logs showed 200 OK the whole time). Wide open origins because
# this only ever runs locally for the demo, never deployed.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serves the real, precomputed sweep-evidence plots (win_plot.png,
# coverage_plot.png) generated by scripts/gen_win_plot.py and
# scripts/gen_coverage_plot.py -- these are DEM-sweep results, not something
# recomputed live per job, so they're exposed as static files, not an
# endpoint that implies live computation.
if os.path.isdir("demo"):
    app.mount("/evidence", StaticFiles(directory="demo"), name="evidence")

DB_PATH = "jobs.db"
PRODUCT_CACHE = {}
PRODUCT_META = {}  # product_id -> its inventory CSV row (metadata only)

# A fast synthetic pair for demo purposes -- the real CH2 x LRO pairs take
# minutes (huge full-resolution rasters, real SPICE lookups); this runs the
# exact same pipeline (align, tile, match, sub-pixel refine, deliverable,
# control network) on a small 512x512 synthetic crater field instead, which
# is what scripts/make_synthetic_deliverable.py already validated as a real,
# trustworthy result (473 inliers, 0.92px residual, trivial_fit=False). Not
# a shortcut or a fake result -- same code path, just fast inputs.
SYNTHETIC_IDS = {"synthetic_a", "synthetic_b"}
_SYNTHETIC_CORNERS = {
    "ul": (-73.45, 42.70), "ur": (-73.45, 42.80),
    "ll": (-73.55, 42.70), "lr": (-73.55, 42.80),
}


def _synthetic_crater_field(size=512, seed=0, n_craters=60):
    rng = np.random.default_rng(seed)
    yy, xx = np.mgrid[0:size, 0:size].astype(np.float32)
    img = 0.5 + 0.05 * rng.standard_normal((size, size)).astype(np.float32)
    for _ in range(n_craters):
        cx, cy = rng.uniform(0, size, size=2)
        r = rng.uniform(6, 28)
        dist = np.sqrt((xx - cx) ** 2 + (yy - cy) ** 2)
        rim = np.exp(-((dist - r) ** 2) / (2 * (r * 0.25) ** 2))
        floor = -0.3 * np.clip(1 - dist / r, 0, 1)
        img += 0.4 * rim + floor
    return np.clip(img, 0.0, 1.0).astype(np.float32)


def _load_synthetic_product(product_id: str) -> Product:
    base = _synthetic_crater_field(size=512, seed=7)
    if product_id == "synthetic_a":
        return Product(array=base, gsd_m=1.0, corners=dict(_SYNTHETIC_CORNERS),
                       source="SYNTH", product_id="synthetic_a")
    warped, _ = make_synthetic_pair(
        base, seed=21, rotation_deg=3.0, scale_range=(0.98, 1.02), translation_frac=0.015
    )
    return Product(array=warped, gsd_m=1.0, corners=dict(_SYNTHETIC_CORNERS),
                   source="SYNTH", product_id="synthetic_b")

# Pseudo-rung requested by the UI's "Auto" option (see pipeline.run_pipeline cascade).
AUTO_RUNG = -1


class RegisterRequest(BaseModel):
    product_a: str
    product_b: str
    rung: int

class JobResponse(BaseModel):
    id: str
    product_a: str
    product_b: str
    rung: int
    status: str
    stage: Optional[str]
    rmse: Optional[float]
    inliers: Optional[int]
    total_matches: Optional[int]
    coverage: Optional[float]
    trivial_fit: Optional[bool]
    created_at: str
    artefact_dir: Optional[str]

def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_db_connection()
    conn.execute('''
        CREATE TABLE IF NOT EXISTS jobs (
            id TEXT PRIMARY KEY,
            product_a TEXT,
            product_b TEXT,
            rung INTEGER,
            status TEXT,
            stage TEXT,
            rmse REAL,
            inliers INTEGER,
            total_matches INTEGER,
            coverage REAL,
            trivial_fit INTEGER,
            created_at TEXT,
            artefact_dir TEXT
        )
    ''')
    # Idempotent migration for a jobs.db that already exists from before the
    # `stage` column was added -- CREATE TABLE IF NOT EXISTS above is a no-op
    # against an existing table, so an older DB file needs this explicitly.
    try:
        conn.execute("ALTER TABLE jobs ADD COLUMN stage TEXT")
    except sqlite3.OperationalError:
        pass  # column already exists
    conn.commit()
    conn.close()

# Each inventory CSV has a different layout: LRO's path column is "path"
# (relative to the repo root); CH2's is "file_path" (relative to
# data/ch2_products/, where the CSV itself lives) and its product_id is a
# full URN (e.g. "urn:isro:isda:ch2_cho.ohr:..."), not a "ch2_"-prefixed id.
_INVENTORY_FILES = [
    {"csv": Path("data/lro_inventory.csv"), "path_col": "path", "base_dir": Path(".")},
    {"csv": Path("data/ch2_products/ch2_inventory.csv"), "path_col": "file_path", "base_dir": Path("data/ch2_products")},
]


def _iter_inventory_rows():
    for spec in _INVENTORY_FILES:
        if not spec["csv"].exists():
            continue
        with open(spec["csv"], "r") as f:
            reader = csv.DictReader(f)
            for row in reader:
                yield spec, row


def _resolve_ch2_label_path(base_dir: Path, rel_path: str) -> "str | None":
    """CH2's inventory CSV file_path column points at a `data/calibrated/...`
    path that does not exist on disk -- the real label XML lives under
    `miscellaneous/calibrated/...` inside the same product directory
    (confirmed against the actual downloaded product tree). The CSV is also
    inconsistent row-to-row: some rows carry a spurious extra "data" segment
    before the real product directory name and some don't, so the product
    directory can't be assumed to be a fixed path position -- try each
    path segment in turn and use whichever one is a real directory.
    """
    candidate = base_dir / rel_path
    if candidate.exists():
        return str(candidate.as_posix())
    parts = [p for p in Path(rel_path.replace("\\", "/")).parts if p not in (".", "..")]
    for part in parts:
        product_dir = base_dir / part
        if product_dir.is_dir():
            matches = list(product_dir.glob("miscellaneous/calibrated/*/*.xml"))
            if matches:
                return str(matches[0].as_posix())
    return None


def load_inventory():
    global PRODUCT_CACHE
    PRODUCT_CACHE.clear()
    PRODUCT_META.clear()
    for spec, row in _iter_inventory_rows():
        pid = row.get("product_id")
        rel_path = row.get(spec["path_col"])
        if not pid or not rel_path:
            continue
        rel_path = rel_path.replace("\\", "/")
        if spec["path_col"] == "file_path":  # CH2
            resolved = _resolve_ch2_label_path(spec["base_dir"], rel_path)
        else:
            resolved = str((spec["base_dir"] / rel_path).as_posix())
        if resolved:
            PRODUCT_CACHE[pid] = resolved
            PRODUCT_META[pid] = dict(row)
    for sid in SYNTHETIC_IDS:
        PRODUCT_CACHE[sid] = "SYNTHETIC"

@app.on_event("startup")
async def startup_event():
    init_db()
    load_inventory()
    print("Models loaded and inventory cached. Ready to serve.")

@app.get("/products")
def get_products():
    products = [row for _spec, row in _iter_inventory_rows()]
    products.append({
        "product_id": "synthetic_a", "gsd_m": "1.0", "subsolar_azimuth_deg": "",
        "center_lat": "", "center_lon": "", "incidence_deg": "", "acquired_utc": "",
    })
    products.append({
        "product_id": "synthetic_b", "gsd_m": "1.0", "subsolar_azimuth_deg": "",
        "center_lat": "", "center_lon": "", "incidence_deg": "", "acquired_utc": "",
    })
    return products


class OverlapRequest(BaseModel):
    product_a: str
    product_b: str


@app.post("/overlap")
def compute_overlap(req: OverlapRequest):
    """Compute footprint overlap fraction between two products."""
    path_a = PRODUCT_CACHE.get(req.product_a)
    path_b = PRODUCT_CACHE.get(req.product_b)
    if not path_a or not path_b:
        raise HTTPException(status_code=400, detail="One or both products not found")

    # Footprints only -- decoding both rasters just to compare four corners
    # each meant a multi-GB CH2 decode on every pair selection in the UI.
    # Falls back to loading the products only when a footprint isn't known
    # yet (a synthetic product, or an LRO product never loaded before).
    fp_a = None if req.product_a in SYNTHETIC_IDS else catalog.footprint(req.product_a, path_a)
    fp_b = None if req.product_b in SYNTHETIC_IDS else catalog.footprint(req.product_b, path_b)
    if fp_a is not None and fp_b is not None:
        overlap_frac, _ = catalog.overlap_fractions(fp_a["corners"], fp_b["corners"])
    else:
        try:
            product_a = load_product_dynamically(req.product_a, path_a)
            product_b = load_product_dynamically(req.product_b, path_b)
        except Exception as e:
            raise HTTPException(status_code=400, detail=f"Failed to load products: {e}")
        overlap_frac = footprint_overlap(product_a, product_b)
    return {
        "product_a": req.product_a,
        "product_b": req.product_b,
        "overlap_percent": round(overlap_frac * 100, 1),
    }


@app.get("/candidates")
def get_candidates(product_id: str):
    """Rank images of the other instrument by footprint overlap with
    `product_id` -- metadata only, no pixels decoded. `not_ingested` counts
    products whose footprint isn't known yet (an LRO product that has never
    been loaded), so a short list is never mistaken for a complete one.
    """
    if product_id not in PRODUCT_CACHE or product_id in SYNTHETIC_IDS:
        raise HTTPException(status_code=404, detail="Product not found in inventory")
    inventory = {pid: {"path": path, **PRODUCT_META.get(pid, {})}
                 for pid, path in PRODUCT_CACHE.items()}
    candidates, not_ingested = catalog.rank_candidates(product_id, inventory)
    return {"product_id": product_id, "candidates": candidates, "not_ingested": not_ingested}


def load_product_dynamically(product_id: str, path: str, overlap_hint=None):
    if product_id in SYNTHETIC_IDS:
        return _load_synthetic_product(product_id)
    if "ch2" in product_id.lower():
        return io_ch2.load_product(path, overlap_hint=overlap_hint)
    else:
        return io_lro.load_product(path)

def _set_stage(job_id: str, stage: str) -> None:
    """Own connection per call: process_job_sync runs on a worker thread via
    asyncio.to_thread, and sqlite3 connections aren't safe to share across
    threads. Best-effort -- a failed stage update shouldn't abort the job
    itself, so swallow errors here rather than let a UI-only nicety take
    down a real registration.
    """
    try:
        conn = get_db_connection()
        conn.execute("UPDATE jobs SET stage = ? WHERE id = ?", (stage, job_id))
        conn.commit()
        conn.close()
    except Exception:
        pass


def process_job_sync(job_id: str, id_a: str, path_a: str, id_b: str, path_b: str, rung: int, artefact_dir: str):
    os.makedirs(artefact_dir, exist_ok=True)
    try:
        _set_stage(job_id, "loading_products")
        # Load whichever product is CH2 SECOND, passing the other (already
        # loaded) product as overlap_hint -- crops CH2's decode to just the
        # overlap region instead of the full raster. Necessary for the
        # process to fit in a memory-constrained deployment: a full CH2
        # decode + align_pair OOM-crashes (exit 137) a real registration
        # under Docker Desktop's default ~7.46GB limit, while cropping brings
        # peak RSS down to a safe margin. Known trade-off, accepted as the
        # lesser evil versus a hard crash: cropping flipped sift-rung0
        # well_determined on 2 of 8 real pairs (and improved one). It is not
        # the crop-local normalisation -- isolated and ruled out -- so the
        # cause is unidentified; see io_ch2.load_product and
        # docs/research/ch2_crop_validation.json.
        a_is_ch2 = "ch2" in id_a.lower() and id_a not in SYNTHETIC_IDS
        b_is_ch2 = "ch2" in id_b.lower() and id_b not in SYNTHETIC_IDS
        if a_is_ch2 and not b_is_ch2:
            product_b = load_product_dynamically(id_b, path_b)
            product_a = load_product_dynamically(id_a, path_a, overlap_hint=product_b)
        elif b_is_ch2 and not a_is_ch2:
            product_a = load_product_dynamically(id_a, path_a)
            product_b = load_product_dynamically(id_b, path_b, overlap_hint=product_a)
        else:
            product_a = load_product_dynamically(id_a, path_a)
            product_b = load_product_dynamically(id_b, path_b)

        # We determine the matcher based on rung. 0 -> sift, 1 -> mod-x (which is mapped to "sift" rung 1 in some code, or "sift" but rung 1. In pipeline it takes matcher="sift" and rung=rung)
        matcher = "sift"
        if rung == 2:
            matcher = "lightglue"

        _set_stage(job_id, "aligning_and_matching")
        # rung == AUTO_RUNG: SIFT first, rung 1 only if SIFT's fit is unreliable.
        out = run_pipeline(product_a, product_b, matcher=matcher, rung=max(rung, 0), align=True,
                           cascade=(rung == AUTO_RUNG), verify=(rung == AUTO_RUNG))
        mr = out["match_result"]
        result = MatchResult(
            pts_a=mr["pts_a"], pts_b=mr["pts_b"], scores=mr["scores"],
            inlier_mask=mr["inlier_mask"], transform=mr["transform"], matcher=mr["matcher"],
            shape_a=mr["shape_a"], shape_b=mr["shape_b"], runtime_s=mr["runtime_s"],
        )
        _set_stage(job_id, "writing_deliverable")
        metrics = build_deliverable(product_a, product_b, result, artefact_dir)
        # Independent-fit agreement (Auto only; None for a single fixed matcher).
        # Stored beside the metrics so the UI can show it without a schema change.
        metrics["agreement"] = out["config"].get("agreement")
        with open(os.path.join(artefact_dir, "metrics.json"), "w") as handle:
            json.dump(metrics, handle, indent=2, allow_nan=False)
        write_control_network(
            result, product_a, product_b,
            os.path.join(artefact_dir, "control_network.net"),
            network_id=f"SIH26166_{job_id}", inliers_only=True,
        )
        return metrics
    except Exception as e:
        traceback.print_exc()
        raise e

async def process_job(job_id: str, id_a: str, path_a: str, id_b: str, path_b: str, rung: int):
    artefact_dir = f"data/jobs/{job_id}"
    conn = get_db_connection()
    try:
        metrics = await asyncio.to_thread(process_job_sync, job_id, id_a, path_a, id_b, path_b, rung, artefact_dir)
        rmse = metrics.get("reprojection_residual")
        inliers = metrics.get("inlier_count")
        total_matches = metrics.get("total_matches")
        coverage = metrics.get("occupied_fraction")
        trivial_fit = metrics.get("trivial_fit")

        conn.execute('''
            UPDATE jobs
            SET status = 'completed', rmse = ?, inliers = ?, total_matches = ?,
                coverage = ?, trivial_fit = ?, artefact_dir = ?
            WHERE id = ?
        ''', (rmse, inliers, total_matches, coverage, trivial_fit, artefact_dir, job_id))
    except Exception as e:
        conn.execute('''
            UPDATE jobs
            SET status = 'failed', artefact_dir = ?
            WHERE id = ?
        ''', (artefact_dir, job_id))
    finally:
        conn.commit()
        conn.close()

@app.post("/register")
async def register_job(req: RegisterRequest, background_tasks: BackgroundTasks):
    path_a = PRODUCT_CACHE.get(req.product_a)
    path_b = PRODUCT_CACHE.get(req.product_b)
    
    if not path_a or not path_b:
        raise HTTPException(status_code=400, detail="One or both products not found in inventory")

    conn = get_db_connection()
    existing_job = conn.execute('''
        SELECT id FROM jobs 
        WHERE product_a = ? AND product_b = ? AND rung = ? AND status = 'completed'
        ORDER BY created_at DESC LIMIT 1
    ''', (req.product_a, req.product_b, req.rung)).fetchone()
    
    if existing_job:
        conn.close()
        return {"job_id": existing_job["id"]}

    job_id = str(uuid.uuid4())
    created_at = datetime.utcnow().isoformat()
    
    conn.execute('''
        INSERT INTO jobs (id, product_a, product_b, rung, status, created_at)
        VALUES (?, ?, ?, ?, 'pending', ?)
    ''', (job_id, req.product_a, req.product_b, req.rung, created_at))
    conn.commit()
    conn.close()
    
    background_tasks.add_task(process_job, job_id, req.product_a, path_a, req.product_b, path_b, req.rung)
    return {"job_id": job_id}

@app.get("/jobs/{job_id}", response_model=JobResponse)
def get_job(job_id: str):
    conn = get_db_connection()
    row = conn.execute("SELECT * FROM jobs WHERE id = ?", (job_id,)).fetchone()
    conn.close()
    if not row:
        raise HTTPException(status_code=404, detail="Job not found")
    return dict(row)

@app.get("/jobs/{job_id}/artefacts/{filename}")
def get_job_artefact(job_id: str, filename: str):
    conn = get_db_connection()
    row = conn.execute("SELECT artefact_dir FROM jobs WHERE id = ?", (job_id,)).fetchone()
    conn.close()
    
    if not row:
        raise HTTPException(status_code=404, detail="Job not found")
    
    artefact_dir = row["artefact_dir"]
    if not artefact_dir:
        raise HTTPException(status_code=404, detail="Artefacts not ready yet")
        
    try:
        base_dir = Path(artefact_dir).resolve(strict=False)
        file_path = Path(os.path.join(base_dir, filename)).resolve(strict=False)
        
        # Path traversal prevention
        if base_dir not in file_path.parents and file_path != base_dir:
            raise HTTPException(status_code=403, detail="Invalid file path")
    except Exception:
        raise HTTPException(status_code=403, detail="Invalid file path")
        
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Artefact file not found")
        
    return FileResponse(str(file_path))


# Serve frontend build if it exists
if os.path.isdir('frontend/dist'):
    app.mount('/', StaticFiles(directory='frontend/dist', html=True), name='frontend')
