import asyncio
import csv
import json
import sqlite3
import os
import uuid
import traceback
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from fastapi import FastAPI, BackgroundTasks, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

import numpy as np

from src.pipeline import run_pipeline
from src.deliverable import build_deliverable
from src.cnet import write_control_network
from src.types import MatchResult, Product
import src.io_lro as io_lro
import src.io_ch2 as io_ch2
from tests.make_synthetic import make_synthetic_pair

app = FastAPI(title="LunarMatch API", description="API and Job Store for Member 5")

# The frontend runs on a different origin (Vite dev server, localhost:3000)
# than this API (127.0.0.1:8000) -- without CORS headers the browser blocks
# every fetch() call with no useful error, which is exactly what surfaced as
# "Failed to connect to LunarMatch backend" despite the API being reachable
# (curl/server logs showed 200 OK the whole time). Wide open origins because
# this only ever runs locally for the demo, never deployed.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serves the real, precomputed sweep-evidence plots (win_plot.png,
# coverage_plot.png) generated by scripts/gen_win_plot.py and
# scripts/gen_coverage_plot.py -- these are DEM-sweep results, not something
# recomputed live per job, so they're exposed as static files, not an
# endpoint that implies live computation.
if os.path.isdir("demo"):
    app.mount("/evidence", StaticFiles(directory="demo"), name="evidence")

DB_PATH = "jobs.db"
PRODUCT_CACHE = {}

# A fast synthetic pair for demo purposes -- the real CH2 x LRO pairs take
# minutes (huge full-resolution rasters, real SPICE lookups); this runs the
# exact same pipeline (align, tile, match, sub-pixel refine, deliverable,
# control network) on a small 512x512 synthetic crater field instead, which
# is what scripts/make_synthetic_deliverable.py already validated as a real,
# trustworthy result (473 inliers, 0.92px residual, trivial_fit=False). Not
# a shortcut or a fake result -- same code path, just fast inputs.
SYNTHETIC_IDS = {"synthetic_a", "synthetic_b"}
_SYNTHETIC_CORNERS = {
    "ul": (-73.45, 42.70), "ur": (-73.45, 42.80),
    "ll": (-73.55, 42.70), "lr": (-73.55, 42.80),
}


def _synthetic_crater_field(size=512, seed=0, n_craters=60):
    rng = np.random.default_rng(seed)
    yy, xx = np.mgrid[0:size, 0:size].astype(np.float32)
    img = 0.5 + 0.05 * rng.standard_normal((size, size)).astype(np.float32)
    for _ in range(n_craters):
        cx, cy = rng.uniform(0, size, size=2)
        r = rng.uniform(6, 28)
        dist = np.sqrt((xx - cx) ** 2 + (yy - cy) ** 2)
        rim = np.exp(-((dist - r) ** 2) / (2 * (r * 0.25) ** 2))
        floor = -0.3 * np.clip(1 - dist / r, 0, 1)
        img += 0.4 * rim + floor
    return np.clip(img, 0.0, 1.0).astype(np.float32)


def _load_synthetic_product(product_id: str) -> Product:
    base = _synthetic_crater_field(size=512, seed=7)
    if product_id == "synthetic_a":
        return Product(array=base, gsd_m=1.0, corners=dict(_SYNTHETIC_CORNERS),
                       source="SYNTH", product_id="synthetic_a")
    warped, _ = make_synthetic_pair(
        base, seed=21, rotation_deg=3.0, scale_range=(0.98, 1.02), translation_frac=0.015
    )
    return Product(array=warped, gsd_m=1.0, corners=dict(_SYNTHETIC_CORNERS),
                   source="SYNTH", product_id="synthetic_b")

class RegisterRequest(BaseModel):
    product_a: str
    product_b: str
    rung: int

class JobResponse(BaseModel):
    id: str
    product_a: str
    product_b: str
    rung: int
    status: str
    rmse: Optional[float]
    inliers: Optional[int]
    total_matches: Optional[int]
    coverage: Optional[float]
    trivial_fit: Optional[bool]
    created_at: str
    artefact_dir: Optional[str]

def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_db_connection()
    conn.execute('''
        CREATE TABLE IF NOT EXISTS jobs (
            id TEXT PRIMARY KEY,
            product_a TEXT,
            product_b TEXT,
            rung INTEGER,
            status TEXT,
            rmse REAL,
            inliers INTEGER,
            total_matches INTEGER,
            coverage REAL,
            trivial_fit INTEGER,
            created_at TEXT,
            artefact_dir TEXT
        )
    ''')
    conn.commit()
    conn.close()

# Each inventory CSV has a different layout: LRO's path column is "path"
# (relative to the repo root); CH2's is "file_path" (relative to
# data/ch2_products/, where the CSV itself lives) and its product_id is a
# full URN (e.g. "urn:isro:isda:ch2_cho.ohr:..."), not a "ch2_"-prefixed id.
_INVENTORY_FILES = [
    {"csv": Path("data/lro_inventory.csv"), "path_col": "path", "base_dir": Path(".")},
    {"csv": Path("data/ch2_products/ch2_inventory.csv"), "path_col": "file_path", "base_dir": Path("data/ch2_products")},
]


def _iter_inventory_rows():
    for spec in _INVENTORY_FILES:
        if not spec["csv"].exists():
            continue
        with open(spec["csv"], "r") as f:
            reader = csv.DictReader(f)
            for row in reader:
                yield spec, row


def _resolve_ch2_label_path(base_dir: Path, rel_path: str) -> "str | None":
    """CH2's inventory CSV file_path column points at a `data/calibrated/...`
    path that does not exist on disk -- the real label XML lives under
    `miscellaneous/calibrated/...` inside the same product directory
    (confirmed against the actual downloaded product tree). The CSV is also
    inconsistent row-to-row: some rows carry a spurious extra "data" segment
    before the real product directory name and some don't, so the product
    directory can't be assumed to be a fixed path position -- try each
    path segment in turn and use whichever one is a real directory.
    """
    candidate = base_dir / rel_path
    if candidate.exists():
        return str(candidate.as_posix())
    parts = [p for p in Path(rel_path.replace("\\", "/")).parts if p not in (".", "..")]
    for part in parts:
        product_dir = base_dir / part
        if product_dir.is_dir():
            matches = list(product_dir.glob("miscellaneous/calibrated/*/*.xml"))
            if matches:
                return str(matches[0].as_posix())
    return None


def load_inventory():
    global PRODUCT_CACHE
    PRODUCT_CACHE.clear()
    for spec, row in _iter_inventory_rows():
        pid = row.get("product_id")
        rel_path = row.get(spec["path_col"])
        if not pid or not rel_path:
            continue
        if spec["path_col"] == "file_path":  # CH2
            resolved = _resolve_ch2_label_path(spec["base_dir"], rel_path)
        else:
            resolved = str((spec["base_dir"] / rel_path).as_posix())
        if resolved:
            PRODUCT_CACHE[pid] = resolved
    for sid in SYNTHETIC_IDS:
        PRODUCT_CACHE[sid] = "SYNTHETIC"

@app.on_event("startup")
async def startup_event():
    init_db()
    load_inventory()
    print("Models loaded and inventory cached. Ready to serve.")

@app.get("/products")
def get_products():
    products = [row for _spec, row in _iter_inventory_rows()]
    products.append({
        "product_id": "synthetic_a", "gsd_m": "1.0", "subsolar_azimuth_deg": "",
        "center_lat": "", "center_lon": "", "incidence_deg": "", "acquired_utc": "",
    })
    products.append({
        "product_id": "synthetic_b", "gsd_m": "1.0", "subsolar_azimuth_deg": "",
        "center_lat": "", "center_lon": "", "incidence_deg": "", "acquired_utc": "",
    })
    return products

def load_product_dynamically(product_id: str, path: str):
    if product_id in SYNTHETIC_IDS:
        return _load_synthetic_product(product_id)
    if "ch2" in product_id.lower():
        return io_ch2.load_product(path)
    else:
        return io_lro.load_product(path)

def process_job_sync(job_id: str, id_a: str, path_a: str, id_b: str, path_b: str, rung: int, artefact_dir: str):
    os.makedirs(artefact_dir, exist_ok=True)
    try:
        product_a = load_product_dynamically(id_a, path_a)
        product_b = load_product_dynamically(id_b, path_b)
        
        # We determine the matcher based on rung. 0 -> sift, 1 -> mod-x (which is mapped to "sift" rung 1 in some code, or "sift" but rung 1. In pipeline it takes matcher="sift" and rung=rung)
        matcher = "sift"
        if rung == 2:
            matcher = "lightglue"

        out = run_pipeline(product_a, product_b, matcher=matcher, rung=rung, align=True)
        mr = out["match_result"]
        result = MatchResult(
            pts_a=mr["pts_a"], pts_b=mr["pts_b"], scores=mr["scores"],
            inlier_mask=mr["inlier_mask"], transform=mr["transform"], matcher=mr["matcher"],
            shape_a=mr["shape_a"], shape_b=mr["shape_b"], runtime_s=mr["runtime_s"],
        )
        metrics = build_deliverable(product_a, product_b, result, artefact_dir)
        write_control_network(
            result, product_a, product_b,
            os.path.join(artefact_dir, "control_network.net"),
            network_id=f"SIH26166_{job_id}", inliers_only=True,
        )
        return metrics
    except Exception as e:
        traceback.print_exc()
        raise e

async def process_job(job_id: str, id_a: str, path_a: str, id_b: str, path_b: str, rung: int):
    artefact_dir = f"data/jobs/{job_id}"
    conn = get_db_connection()
    try:
        metrics = await asyncio.to_thread(process_job_sync, job_id, id_a, path_a, id_b, path_b, rung, artefact_dir)
        rmse = metrics.get("reprojection_residual")
        inliers = metrics.get("inlier_count")
        total_matches = metrics.get("total_matches")
        coverage = metrics.get("occupied_fraction")
        trivial_fit = metrics.get("trivial_fit")

        conn.execute('''
            UPDATE jobs
            SET status = 'completed', rmse = ?, inliers = ?, total_matches = ?,
                coverage = ?, trivial_fit = ?, artefact_dir = ?
            WHERE id = ?
        ''', (rmse, inliers, total_matches, coverage, trivial_fit, artefact_dir, job_id))
    except Exception as e:
        conn.execute('''
            UPDATE jobs
            SET status = 'failed', artefact_dir = ?
            WHERE id = ?
        ''', (artefact_dir, job_id))
    finally:
        conn.commit()
        conn.close()

@app.post("/register")
async def register_job(req: RegisterRequest, background_tasks: BackgroundTasks):
    path_a = PRODUCT_CACHE.get(req.product_a)
    path_b = PRODUCT_CACHE.get(req.product_b)
    
    if not path_a or not path_b:
        raise HTTPException(status_code=400, detail="One or both products not found in inventory")

    job_id = str(uuid.uuid4())
    created_at = datetime.utcnow().isoformat()
    
    conn = get_db_connection()
    conn.execute('''
        INSERT INTO jobs (id, product_a, product_b, rung, status, created_at)
        VALUES (?, ?, ?, ?, 'pending', ?)
    ''', (job_id, req.product_a, req.product_b, req.rung, created_at))
    conn.commit()
    conn.close()
    
    background_tasks.add_task(process_job, job_id, req.product_a, path_a, req.product_b, path_b, req.rung)
    return {"job_id": job_id}

@app.get("/jobs/{job_id}", response_model=JobResponse)
def get_job(job_id: str):
    conn = get_db_connection()
    row = conn.execute("SELECT * FROM jobs WHERE id = ?", (job_id,)).fetchone()
    conn.close()
    if not row:
        raise HTTPException(status_code=404, detail="Job not found")
    return dict(row)

@app.get("/jobs/{job_id}/artefacts/{filename}")
def get_job_artefact(job_id: str, filename: str):
    conn = get_db_connection()
    row = conn.execute("SELECT artefact_dir FROM jobs WHERE id = ?", (job_id,)).fetchone()
    conn.close()
    
    if not row:
        raise HTTPException(status_code=404, detail="Job not found")
    
    artefact_dir = row["artefact_dir"]
    if not artefact_dir:
        raise HTTPException(status_code=404, detail="Artefacts not ready yet")
        
    try:
        base_dir = Path(artefact_dir).resolve(strict=False)
        file_path = Path(os.path.join(base_dir, filename)).resolve(strict=False)
        
        # Path traversal prevention
        if base_dir not in file_path.parents and file_path != base_dir:
            raise HTTPException(status_code=403, detail="Invalid file path")
    except Exception:
        raise HTTPException(status_code=403, detail="Invalid file path")
        
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Artefact file not found")
        
    return FileResponse(str(file_path))
